sudo: required

language: cpp

# this step is for adding additional dependencies required for the project that 
# are common across the various build configurations.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsqlite3-dev libxll-dev libfltk1.3-dev libxaw-dev
  - sudo apt-get install -y libxmu-dev libxpm-dev libxft-dev libxt-dev libfontconfig1-dev

 


