language: c++

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
		        - george-edison55-precise-backports # cmake 3.2.3
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - g++-6
            - cmake
            - cmake-data
            
     - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
		        - george-edison55-precise-backports # cmake 3.2.3
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - cmake-data
  
  
script: ./reconfig.sh


