 language: cpp
 
 compiler:
   - gcc
   
 addons:
    apt:
      sources:
        - george-edison55-precise-backports # cmake 3.2.3
        - ubuntu-toolchain-r-test
        
      packages:
        - g++-6
        - cmake
        - cmake-data
        - libfltk1.3-dev
      
   
 script:
   - cd /home/travis
   - git clone https://github.com/leethomason/tinyxml2.git
   - cd tinyxml2
   - make all
   - cd ..
   - cd /KAPSARC/KTAB
   - ./reconfig.sh
