language: cpp

compiler:
  - clang
  - gcc
  
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
      - ubuntu-toolchain-r-test # source for g++-5
      - llvm-toolchain-precise 
      - llvm-toolchain-precise-3.7 # source for clang-3.8
      
    packages:
      - clang-3.8
      - g++-5
      - cmake
      - cmake-data
      

install:
  - sudo apt-get update
  - sudo apt-get install libtinyxml2-dev
  
script: ./reconfig.sh


