language: cpp

sudo: required

# this step is for making alterations to the default environment before
# installing additional dependencies.
before_install:
  - sudo apt-get remove cmake   # default Ubuntu only has cmake 2.8.7!

# this step is for adding additional dependencies required for the project that 
# are common across the various build configurations.
install:
  # first install newer cmake version
  - sudo apt-get install --assume-yes software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.0
  - sudo apt-get update --assume-yes
  - sudo apt-get install --assume-yes cmake
  - cmake --version  # This allows us to confirm which version of cmake has been installed.
  
  # next install additional required dependencies
  - sudo apt-get install --assume-yes libsqlite3-0 libx11-6 libfltk1.3 libxaw7
  - sudo apt-get install --assume-yes libxmu6 libxpm4 libxft2 libxt6 libfontconfig1
  
# this step runs a custom build script that builds the various components of
# KTAB in the required order.
script:     
 - ./reconfig.sh
