sudo: required

language: cpp

# this step is for adding additional dependencies required for the project that 
# are common across the various build configurations.
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsqlite3-0 libx11-6 libfltk1.3 libxaw7
  - sudo apt-get install -y libxmu6 libxpm4 libxft2 libxt6 libfontconfig1
