language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      branches:
        only:
          - master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - C_COMPILER=gcc-4.9
        - CXX_COMPILER=g++-4.9

before_install:  # necessary because Travis overwrites CXX and CC!
  - if [[ $TRAVIS_OS_NAME == linux ]]; then export CXX=$CXX_COMPILER CC=$C_COMPILER; fi

install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install qt5-default; fi #install Qt5 libraries
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo bash ./install-linux-deps.sh; fi  # Why do I need permission?

  # install tinyxml2
  - git clone https://github.com/leethomason/tinyxml2.git
  - cd tinyxml2
  - cmake . -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON && sudo make install

  # install and build Elpp
  - cd $TRAVIS_BUILD_DIR
  # creating a dir to clone and build Elpp (Created due to name conflict with original folder "easyloggingpp"
  - mkdir temp_elpp
  - cd temp_elpp
  - git clone https://github.com/muflihun/easyloggingpp.git
  - mv $TRAVIS_BUILD_DIR/easyloggingpp/CMakeLists.txt $TRAVIS_BUILD_DIR/temp_elpp/easyloggingpp
  - cd easyloggingpp
  - mkdir build 
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install 
  - cd $TRAVIS_BUILD_DIR

before_script:
#Set the script to execute
  - chmod a+x reconfig.sh
  - chmod a+x KTAB_Test_Apps.sh

script:
  - ./reconfig.sh

#after_success:
  #- ./examples/smp/smpc --csv ./examples/smp/doc/SOE-Pol-Comp.csv
  #- ./examples/smp/smpc --csv ./examples/smp/doc/dummyData_3Dim.csv
  #- ./KTAB/kmodel/demomodel --emod
  - ./KTAB_Test_Apps.sh

