language: cpp

compiler:
  - clang
  - gcc
  
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      
    packages:
      - clang-3.8
      - g++-5
      - cmake
      - cmake-data
  
script: ./reconfig.sh


